version: "3.3"
services:
  router:
    build:
      context: .
      dockerfile: DockerfileRouter
    ports:
      - 5002:5002
      - 5001:5001

  lambda:
    build:
      context: .
      dockerfile: DockerfileLambda
